name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./nginx-golang/backend/ --file ./nginx-golang/backend/Dockerfile --tag alvanxpgo:$(date +%s)
